title: Rick's Fake Blog
author: Ricky Dicky
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is not a real blog. It's a page built during the course of following a tutorial to learn GitHub Pages

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  eggzotic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
